version: "3"

services:
  app:
    build: ./public
    ports: 
      - "8080:8080"
    volumes:
      - .:/usr/public

  server:
    build: ./server
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/server

  peer-server:
    build: ./peer-server
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/peer-server



